"""Operation Tidebreak: storyboard data (phase 2, revision 1).

One source for the storyboard page, shots.csv, shots.md and ASSET_REQUESTS.md.
Build with:  python3 storyboard/build_storyboard.py

Conventions
- `dur` is screen time in seconds at 24 fps; frames are computed from it.
- `clock` is real mission time at the start of the shot (T+h:mm:ss from warp exit).
- `real` says how the shot treats time: "1:1", "compressed N×" or "slowed N×".
- `rules` cite doctrine rule IDs (doctrine/LREF_doctrine.md, doctrine/Defence_doctrine.md).
- `assets` cite IDs in ASSETS below; `rig` names Endeavor rig properties
  (pack/project_docs/README_blender_project.md) or new ones requested in ASSETS.
- `cost` is the render cost class in RENDER_CLASSES.
- `sketch` is a call into the sketch library in build_storyboard.py; `render`
  is a current Blender frame from the modelling session used as reference.
"""

TITLE = "Operation Tidebreak"
REVISION = "Revision 1 · phase 2 draft for review"
FPS = 24
FORMAT = "2.39:1 · 1920×804 · 24 fps · Cycles"

# ---------------------------------------------------------------- mission
# Real timeline, from the approved doctrines and doctrine/working_numbers.md.
# Geometry: inertial frame with +x pointing from Maren to the rock "the Lee"
# at T+5:09, when Site 1 and Breakwater pass under it (see MAPS).
PHASES = [
    ("T+0:00", "T+0:25", "Arrival", "Exit at 450,000 km, near rest relative to Maren. Shields parked with the Nauvoo. Picture and net up. Wave one away at Skerry (T+0:18)."),
    ("T+0:25", "T+0:59", "Turn and burn", "1 g along the approach line for 34 min: 0 → 20 km/s over 20,400 km."),
    ("T+0:59", "T+3:20", "Coast", "20 km/s, bow on Maren, fins out edge-on once Skerry's laser is gone (T+1:04)."),
    ("T+3:20", "T+4:35", "The Breakers", "Fins stowed in the debris. Ambush, Canterbury lost, drones, Normandy lost. 89,600 km at 20 km/s."),
    ("T+4:35", "T+5:09", "Turnover", "Flip (49 s) and brake at 1 g for 34 min into the lee of the Lee, an 18 km rock 150,000 km out."),
    ("T+5:09", "T+5:45", "The Lee", "The rock hides the fleet from Site 1 and Breakwater. Venting, the fin hit, the broadside, the lance."),
    ("T+5:45", "T+7:05", "Final approach", "1 g to 20 km/s, then coast down Site 1's line. Spend wave (launched T+5:42) arrives T+6:01. Skerry's net met at T+6:40."),
    ("T+6:55", "T+7:29", "Hammer and anvil", "Kill wave arrives T+7:03 within ~1 s; Casaba spears cut Breakwater's drive. Astrid's spinal from 14,700 km at T+7:26, hit T+7:29."),
    ("T+7:29", "T+9:10", "Terms", "Breakwater breaks up. MDC asks for terms (T+7:45); Site 1 goes dark; the fleet vents at last."),
]

KEY_NUMBERS = [
    ("Warp exit and shield park", "450,000 km from Maren", "LREF O1, A-01/A-02"),
    ("The Breakers", "120,000–260,000 km, ±25°", "Defence §4.1"),
    ("The Lee (anchor rock)", "~18 km across, 150,000 km out", "D5"),
    ("Skerry", "380,000 km, 40° off the approach line", "Defence §4"),
    ("Breakwater", "synchronous orbit, 42,164 km, over Site 1", "H-04"),
    ("Cruise speed", "20 km/s (O8: ≤ ~20 km/s through prepared space)", "WN §6"),
    ("Burns", "1 g, 34 min each way; flips 49 s (Endeavor), 58 s (Astrid)", "WN §6"),
    ("Light-lag", "1.0 s to Skerry from the fleet at T+1:04; 0.5 s to Site 1 from the Lee", "WN §5"),
    ("Spinal no-escape vs crippled Breakwater", "≤ 14,700 km with 20 km/s closing; flight 184 s", "WN §2"),
    ("Endeavor heat sink", "20 TJ: 94 % full on reaching the Lee", "WN §4"),
]

# ---------------------------------------------------------------- forces
FLEET = [
    ("L.R.E.F.S. Astrid", "Hanuman heavy cruiser", "Flagship, 'Tidebreak Actual'. Spinal cannon, AVPSA. Trails the line by ~8,000 km."),
    ("L.R.E.F.S. Endeavor", "Ryland cruiser", "The line. Loses its port fin at the Lee."),
    ("Infinity · Pillar of Autumn · Galactica", "Hedgehog frigates", "The pack: wave one (Skerry), wave two (spend), wave three (kill). Infinity goes home dry."),
    ("Donnager", "Gun frigate", "Medium-range hammer; engages the Compact frigate at the Lee."),
    ("Excelsior", "PD frigate", "Guards the Nauvoo and the parked shields."),
    ("Canterbury", "ECW destroyer", "Lost in the Breakers ambush (T+3:52)."),
    ("Extenuating Circumstances", "ECW destroyer", "Holds the net alone after the Canterbury."),
    ("Rocinante · Tantive IV · Wallfish · Normandy", "Corvettes", "Drone screen. Normandy lost to a plasma-bomb drone (T+4:25)."),
    ("Nauvoo", "Tender", "Holds the shield park 450,000 km out."),
]
DEFENDERS = [
    ("Breakwater", "Warpless monitor", "Synchronous orbit over Site 1. Guns never get a shot: the LREF stays outside their no-escape range."),
    ("Site 1 (of 4)", "Ground laser, 2 GW", "The only site that can see Breakwater's sky. Never struck (ROE)."),
    ("Skerry", "Moon complex", "Mass driver (3 rounds launched at T+0:04), laser battery, drone depot. Struck by wave one."),
    ("The Breakers garrison", "Emplacements", "Cold pods, railgun platforms, parked drones."),
    ("Inner ring", "12 emplacements", "PD umbrella around Breakwater."),
    ("Compact frigate", "Frigate", "Ambushes the Endeavor at the Lee from behind a rock 60 km off."),
]

# ---------------------------------------------------------------- assets
# status: "built" (exists), "extend" (built, needs additions), "new"
# concept: True when it must go through concept sheets first (user rule:
# new weapon designs are picked from concept sheets before modelling).
ASSETS = {
    "EN": ("L.R.E.F.S. Endeavor (rigged)", "built", False, "Hero ship. All rig properties per the README."),
    "EN-FIN": ("Endeavor: per-fin control and damage", "extend", False, "Per-fin deploy properties (fin_port, fin_starboard, fin_dorsal, fin_ventral) instead of one radiator_deploy; a shattered port fin, a cut-loose fin drifting away, and the stump state for later shots."),
    "EN-MAST": ("Endeavor: sensor-mast shutters", "extend", False, "A `mast_shutter` property: armoured shutters close over the mast windows when a laser paints them."),
    "EN-DMG": ("Endeavor: hull scars", "extend", False, "Scorching and spall on the port belt from the Compact frigate's slug (shot 26) carried into shots 27–37."),
    "M1C": ("M-1C twin railcannon", "built", False, "On the Endeavor; reused scaled on other ships."),
    "MSL": ("Missile asset (26 m, plume, thrust)", "built", False, "Base for every missile variant."),
    "MSL-V": ("Missile variants", "new", False, "Hedgehog capital-ship killer (hardened ablative nose, spin), small multi-pack missile, decoy, EW missile, Compact belt-pod missile."),
    "AST": ("L.R.E.F.S. Astrid (Hanuman heavy cruiser)", "new", False, "Hero. Spinal cannon along the full hull with muzzle; AVPSA ~100 m articulated dish; 8 stacked fins (retract for warp); ≥25 laser arrays and ≥19 M-1C turrets; dense CIWS and PD lasers; twin hab rings; warp rings; shield launch. Art exists (Sir_Lazz)."),
    "GI": ("Garibaldi-Ivanova frigate hull", "new", False, "Hero. ~420 m; module bay; warp rings fore and aft; impact shield; spinning hab section; reactor, engines, radiators. Art exists."),
    "GI-MAV": ("Hedgehog (MAV) module", "new", False, "~360 pods (single capital-ship-killer pods fore, multi-silo packs aft); pod-door and ripple-launch rig. Art exists."),
    "GI-GUN": ("Gun module (4 large kinetic batteries)", "new", True, "Concept sheet first (new weapon design). Probably an up-scaled M-1C family."),
    "GI-PD": ("PD module (lasers, CIWS, kill-cloud dispensers)", "new", True, "Concept sheet first."),
    "DD": ("ECW destroyer", "new", False, "Hero. ~200 m; parabolic antenna over the aft third; retractable sensor booms; drone/satellite bays; CIWS; stern radiators. Art exists."),
    "DD-BRK": ("Destroyer break-up (Canterbury)", "new", False, "Fractured variant: holed stern to bow, reactor scram flash, venting, the hull parting in two."),
    "CV": ("Corvette class", "new", True, "No reference art: concept sheet first. 50–150 m, fast, anti-drone weapons."),
    "CV-BRK": ("Corvette destruction (Normandy)", "new", False, "Plasma-bomb hit and break-up variant."),
    "TND": ("Nauvoo, fleet tender", "new", True, "No reference art: concept sheet first. Cargo frames, shield cradles, a crane arm; can stay a distant shape."),
    "SHD": ("Parked impact shields", "extend", False, "The Endeavor's gold shield exists; the other ships' shields come with their assets. Needs a parked cluster set-up."),
    "DRN-L": ("LREF drones", "new", True, "Concept sheet first: picket, decoy, PD and EW drones."),
    "BW": ("Breakwater, Compact monitor", "new", True, "Concept sheet first. ~1,800 m warpless monitor: no warp rings or shield, ~2 m armour belt, 6 twin heavy turrets, 24 PD lasers, 40 CIWS, 64 missile cells, armoured louvred radiators."),
    "BW-BRK": ("Breakwater break-up", "new", False, "Casaba breach on the drive section, spinal entry wound amidships, secondaries, the back breaking."),
    "CF": ("Compact frigate", "new", True, "Concept sheet first. ~350 m, coilgun and missiles; break-up variant."),
    "DRN-C": ("Compact drones", "new", True, "Concept sheet first: plasma-bomb drone and kill-cloud drone; a cold 'hide' on a rock."),
    "EMP-POD": ("Cold missile pod on a rock", "new", True, "Concept sheet first. Buried in regolith; petal doors; cold launch."),
    "EMP-RG": ("Breakers railgun platform", "new", True, "Concept sheet first. Buried twin railgun that unmasks, fires a 10-slug salvo, and dies."),
    "RING": ("Inner-ring emplacement", "new", True, "Concept sheet first. Orbital railgun/PD station."),
    "SKR": ("Skerry (moon) and complex", "new", False, "Airless moon ~900 km radius; three mass-driver tracks (~40 km), laser battery, drone depot. Seen from far away: detail can stay modest."),
    "MAREN": ("Maren: planet re-dress", "extend", False, "Re-dress the World-shader planet: new continents and weather, night-side cities, the Site 1 plateau, and the limb for shots 31–37."),
    "BRK": ("The Breakers: debris-torus environment", "new", False, "Faint dust haze and glitter (volumetric or particles), a generic rock set, sparse large rocks at realistic spacing."),
    "LEE": ("The Lee: hero rock", "new", False, "~18 km rubble-pile asteroid with boulders and a few small moonlets; must hold up at close range."),
    "FX-WARP": ("Warp-exit flash", "new", False, "Bubble collapse bloom (comp plus light)."),
    "FX-SWARM": ("Missile swarm", "new", False, "Instanced missiles with plumes; ripple launch; staggered burns."),
    "FX-NUKE": ("Distant nuclear flashes", "new", False, "Point flashes on Skerry's surface, seen from far away."),
    "FX-PD": ("Point-defence fire", "new", False, "CIWS tracer streams and kill clouds, chaff, flares, smoke screens, intercept flashes."),
    "FX-SLUG": ("Slug streaks and impacts", "new", False, "Glints, impact flash, spall cone, shock ring."),
    "FX-BREAK": ("Ship break-up", "new", False, "Cell fracture, venting, debris (shared by DD-BRK, CV-BRK, CF, BW-BRK)."),
    "FX-DRN": ("Drone swarm", "new", False, "Instanced drones, plasma-bomb flashes."),
    "FX-FIN": ("Fin shatter and coolant vapour", "new", False, "Glowing shards, coolant flashing to vapour."),
    "FX-LANCE": ("Plasma lance bolt", "new", False, "Compact toroid: violet-white ring, near-instant."),
    "FX-CAN": ("Canister cloud", "new", False, "Skerry's canister round bursting into a pellet cloud, seen as glints in drone lights."),
    "FX-CASABA": ("Casaba jets", "new", False, "Narrow nuclear plasma spears from 2–4 km standoff."),
    "FX-SPINAL": ("Spinal cannon fire and impact", "new", False, "Muzzle bloom down the Astrid's kilometre barrel; impact flash and spall."),
    "FX-DAZZLE": ("Dazzle and sensor whiteout", "new", False, "Comp: bloom on optics, POV whiteout."),
    "FX-EW": ("EW overlay", "new", False, "Comp: glitch bands on HUD inserts."),
    "HUD": ("Tactical HUD and mission clock", "new", False, "2D comp: plots, tracks, mission clock, heat readouts; one design reused."),
    "SUB": ("Comm subtitles", "new", False, "2D comp: speaker tag + line; voice acting may replace them later."),
}

RENDER_CLASSES = {
    "A": ("Endeavor close-up", "Endeavor patch + FX; ~35 s/frame (measured hero cost)"),
    "B": ("Single hero ship, full view", "~60–90 s/frame"),
    "C": ("Multi-ship or heavy FX", "~2–3 min/frame"),
    "D": ("Wide, distant, simple", "~10–20 s/frame"),
    "E": ("2D comp / HUD", "seconds per frame"),
}

ACTS = [
    ("I", "Arrival", "The fleet arrives slow, parks its shields, reads the system and strikes Skerry first."),
    ("II", "Long reach", "Hours of coasting, then the Breakers: the ambush, the Canterbury, the Astrid's answer."),
    ("III", "The Lee", "Turnover into the lee of a rock: heat, the fin hit, the broadside and the lance."),
    ("IV", "Hammer and anvil", "Down Site 1's line: the spend wave, Skerry's net, the kill wave, the Casaba spears and the spinal shot."),
]

MAPS = {
    "A": "Arrival and long reach (T+0:00 → T+3:20)",
    "B": "The Breakers (T+3:20 → T+5:09)",
    "C": "The Lee (T+5:09 → T+5:45)",
    "D": "Hammer and anvil (T+5:45 → T+7:45)",
}

# ---------------------------------------------------------------- shots
SHOTS = [
    # ------------------------------------------------------------ ACT I
    dict(act="I", title="Black, then a star", dur=6, clock="T+0:00:00", real="1:1",
         cam="EWS · 35 mm · locked off",
         action="Starfield. A point of light swells into a blue-white bloom as the bubble collapses (~5 s). The Endeavor resolves out of it, shield forward, both warp rings glowing, fins stowed as they must be in warp.",
         comm=[], rules=["O1"], vfx="Warp-exit flash", rig=["warp_charge 1→0.3"],
         assets=["EN", "FX-WARP"], sound="Silence. A sub-bass drop as the bubble collapses.",
         cost="B", map="A", render=None,
         sketch="panel([glow(120,50,55,'#9ec8ff',0.55), glow(120,50,14,'#ffffff',0.95), ship('endeavor',120,50,0.45,0)], 11)"),
    dict(act="I", title="Rings cool", dur=4, clock="T+0:00:06", real="1:1",
         cam="CU · 50 mm · slow push along the bow ring",
         action="The front warp ring's emitters fade from blue to dark. A burst of bow RCS trims the drift.",
         comm=[("ENDEAVOR", "Actual, Endeavor. Clean exit. Rings cooling.")],
         rules=["O1"], vfx="Emitter glow fade, RCS puffs", rig=["warp_charge 0.3→0", "rcs_bow pulse"],
         assets=["EN"], sound="Ticking metal and RCS thumps through the hull (camera rides the ring).",
         cost="A", map="A", render="img/bow_v4b_combat.jpg", sketch=None),
    dict(act="I", title="The task group", dur=5, clock="T+0:00:10", real="compressed 7× (13 exits over ~36 s)",
         cam="EWS · 85 mm · long lens, locked off",
         action="Staggered warp flashes, seconds and 50+ km apart: the Astrid, the hedgehog pack, the Donnager, the Excelsior, both destroyers, four corvettes, the Nauvoo. Far beyond, Maren is a blue crescent, Skerry a grey dot, and the Breakers a faint glittering band.",
         comm=[("TIDEBREAK ACTUAL", "Thirteen for thirteen. Everyone's home.")],
         rules=["O1", "D2"], vfx="12 warp flashes, the Breakers' glitter band",
         rig=[], assets=["AST", "GI", "GI-MAV", "DD", "CV", "TND", "MAREN", "SKR", "BRK", "FX-WARP"],
         sound="Distant low thuds, one per exit (score, not diegetic).",
         cost="D", map="A", render=None,
         sketch="panel([planet(214,60,34,'left'), moon(176,22,4), glow(40,40,9,'#9ec8ff',0.6), glow(70,58,7,'#9ec8ff',0.5), glow(26,66,6,'#9ec8ff',0.5), ship('astrid',40,40,0.16,0), ship('hedgehog',70,58,0.2,0), ship('destroyer',26,66,0.35,0), ship('endeavorNoShield',104,48,0.16,0), ship('tender',140,70,0.3,0), '<path d=\"M130,86 Q190,74 240,70\" fill=\"none\" stroke=\"#cfd8e0\" stroke-width=\"0.4\" stroke-dasharray=\"0.6 1.4\" opacity=\"0.6\"/>'], 3)"),
    dict(act="I", title="Shields to the park", dur=5, clock="T+0:03:00", real="compressed 8× (~40 s)",
         cam="MS · 35 mm · behind the shield, looking aft at the bow",
         action="Separation thrusters fire between the front ring's spokes; the gold impact shield backs away and drifts toward a cluster of parked shields where the Nauvoo waits, the Excelsior on guard. Both warp rings stay on the ship. Every shield parked here at near-zero speed can be collected after the battle.",
         comm=[("ENDEAVOR", "Nauvoo, Endeavor. The shield's yours."), ("NAUVOO", "Got it. We'll leave the porch light off.")],
         rules=["O1", "D9", "D11"], vfx="Shield separation, thruster plumes",
         rig=["shield_thrusters 1", "shield_separation 0→400"], assets=["EN", "SHD", "TND", "GI", "GI-PD"],
         sound="Clamp bangs through the ring truss, then quiet.",
         cost="A", map="A", render="img/endeavor_combat_demo_f060.jpg", sketch=None),
    dict(act="I", title="The moon speaks", dur=3, clock="T+0:04:10", real="1:1",
         cam="HUD insert · Astrid telescope feed, 2,000 mm equivalent",
         action="On the telescope feed, a thread of light runs along Skerry's dark limb: the mass driver's track arcing as it throws. Three tracks leave the moon. The plot tags them: impact region, the final approach lane; time of flight, about seven hours.",
         comm=[("ASTRID SENSORS", "Launch on Skerry. Three rounds, heading down our lane."), ("TIDEBREAK ACTUAL", "Noted. They'll be hours.")],
         rules=["HO3", "O2"], vfx="HUD plot, telescope grain", rig=[], assets=["HUD", "SKR"],
         sound="Soft sensor tones.", cost="E", map="A", render=None,
         sketch="panel([moon(120,50,26), '<path d=\"M104,38 Q118,30 134,34\" fill=\"none\" stroke=\"#ffe3b0\" stroke-width=\"0.9\"/>', hud(70,12,100,76), label(74,20,'SKERRY · MASS DRIVER · 3 TRACKS','#e2603f'), label(74,86,'IMPACT: FINAL LANE · TOF 6 h 40 m','#33b3a2')], 5)"),
    dict(act="I", title="The Astrid looks", dur=4, clock="T+0:09:00", real="compressed 60× (the picture builds over ~5 min)",
         cam="MS · 50 mm · the AVPSA dish slewing, cut to HUD insert",
         action="The Astrid's 100 m AVPSA dish slews. On the plot, tracks bloom: Breakwater parked over Site 1, Skerry's battery and tracks, three Compact frigates, forty-plus unknowns in the Breakers. The destroyers' net comes up and the fleet goes radio-silent.",
         comm=[("TIDEBREAK ACTUAL", "Picture's up. Breakwater's parked over their big laser, like the brief said.")],
         rules=["O2", "D10"], vfx="HUD overlay", rig=[], assets=["AST", "HUD"],
         sound="Soft sensor pings.", cost="B", map="A", render=None,
         sketch="panel([ship('astrid',70,56,0.55,-8), hud(140,14,90,72), label(144,24,'BREAKWATER · SYNC ORBIT','#e2603f'), label(144,34,'SITE 1 · 2 GW','#e2603f'), label(144,44,'SKERRY · BATTERY + 3 TRACKS','#e2603f'), label(144,54,'FRIGATES ×3','#e2603f'), label(144,64,'UNKNOWNS ×43 · BREAKERS','#e2603f'), label(144,80,'NET UP · EMCON','#33b3a2')], 21)"),
    dict(act="I", title="Wave one", dur=5, clock="T+0:18:00", real="1:1",
         cam="WS · 24 mm · handheld, off the Infinity's flank",
         action="The Infinity ripple-fires 150 missiles at Skerry in fifteen seconds: pod doors open in waves down the hull, plumes curve into a stream and race away. Skerry is fixed and its laser is the one thing that can burn the fleet's fins on the way in, so it goes first.",
         comm=[("TIDEBREAK ACTUAL", "Infinity, Actual. Wave one, Skerry. Take their laser off the board."), ("INFINITY", "Wave one away.")],
         rules=["O3", "O9", "D3"], vfx="150 missile instances, plumes, pod doors",
         rig=[], assets=["GI", "GI-MAV", "MSL-V", "FX-SWARM"],
         sound="Staccato launch cracks through the hull.", cost="C", map="A", render=None,
         sketch="panel([ship('hedgehog',70,58,1.3,-6), trail('M96,50 Q150,30 230,18','#ffd9a0','0.6 0.9',0.8), trail('M96,54 Q150,36 230,26','#ffd9a0','0.6 0.9',0.6), sparks(170,30,26,40,4)], 7)"),
    dict(act="I", title="Turn and burn", dur=6, clock="T+0:25:00", real="compressed 8× (the turn takes ~49 s)",
         cam="WS · 28 mm · 90° orbit round the Endeavor",
         action="The Endeavor pitches onto the approach line on RCS and its five engines light. Bow first, guns forward, fins stowed. Across the sky the whole group lights up together: 1 g for 34 minutes.",
         comm=[("TIDEBREAK ACTUAL", "All ships, execute. One g.")],
         rules=["O1", "D2"], vfx="Main plumes, RCS",
         rig=["rcs_bow / rcs_stern pulses", "engine_throttle 0→1", "engine_glow"], assets=["EN"],
         sound="Drive roar through the hull, rising.", cost="B", map="A", render=None,
         sketch="panel([plume(160,50,78,0,4), ship('endeavorNoShield',120,50,0.9,0,true)], 13)"),
    # ------------------------------------------------------------ ACT II
    dict(act="II", title="Skerry burns", dur=4, clock="T+1:04:00", real="compressed 5× (~20 s of hits)",
         cam="EWS · 1,200 mm · from the fleet, Skerry a small grey disc",
         action="Pinpricks of white on Skerry's limb: wave one arriving, nose-on to the battery. The light left Skerry a second ago. On the plot the battery goes out and two of three tracks die; the depot burns.",
         comm=[("ASTRID SENSORS", "Splash on Skerry. Their laser's gone. Two tracks down.")],
         rules=["O3", "O9"], vfx="Distant nuclear flashes", rig=[], assets=["SKR", "FX-NUKE"],
         sound="Nothing, then a low swell of score.", cost="D", map="A", render=None,
         sketch="panel([moon(120,50,22), glow(106,40,6,'#ffffff',0.95), glow(112,34,4,'#ffffff',0.9), glow(100,48,3,'#ffffff',0.8)], 9)"),
    dict(act="II", title="Fins edge-on", dur=4, clock="T+1:10:00", real="compressed 5× (fins extend over ~20 s)",
         cam="MS · 40 mm · dead ahead, slightly high",
         action="Coasting at 20 km/s with Skerry's laser gone, the Endeavor points its nose at distant Maren and runs its four fins out. From Site 1 and Breakwater, dead ahead, every fin is edge-on. They glow a dull red.",
         comm=[("ENDEAVOR", "Fins out. Keep the nose on Maren; keep them edge-on.")],
         rules=["D3"], vfx="Fin glow", rig=["radiator_deploy 0.12→1", "heat 0.6", "radiator_glow"],
         assets=["EN"], sound="Hydraulic groan through the hull, then quiet.",
         cost="A", map="A", render="img/orbit_v8d.jpg", sketch=None),
    dict(act="II", title="The Breakers", dur=5, clock="T+3:20:00", real="1:1",
         cam="WS · 24 mm · tracking alongside",
         action="The fins retract before the debris. A faint haze thickens; a single large rock slides past, twenty kilometres off, gone across the frame in two seconds at 20 km/s. Drones and corvettes spread ahead.",
         comm=[("TIDEBREAK ACTUAL", "Entering the Breakers. Fins in. Corvettes, sweep the lane.")],
         rules=["O8", "D3", "D5", "D6"], vfx="Dust haze, glitter, one rock fly-by",
         rig=["radiator_deploy 1→0.12"], assets=["EN", "BRK", "CV", "DRN-L"],
         sound="Low drone; dust ticking on the hull.", cost="C", map="B", render=None,
         sketch="panel([rocks(3,1,40,70,40,60,14,16), ship('endeavorNoShield',150,54,0.7,0), ship('corvette',210,40,1.2,0), ship('drone',226,48,1.4,0), '<rect width=\"240\" height=\"100\" fill=\"#9fb0bc\" opacity=\"0.05\"/>'], 17)"),
    dict(act="II", title="Blind", dur=3, clock="T+3:30:00", real="1:1",
         cam="CU · 85 mm · sensor mast, with POV insert",
         action="Site 1 finds the Endeavor through the haze. The mast's optics flare and the POV feed whites out; armoured shutters slam over the windows.",
         comm=[("ENDEAVOR SENSORS", "Site One is painting us. Shutters on the mast.")],
         rules=["HO5", "D10"], vfx="Dazzle bloom on optics, POV whiteout",
         rig=["mast_shutter 0→1 (new)"], assets=["EN", "EN-MAST", "FX-DAZZLE"],
         sound="A static howl on the feed, cut by the shutter slam.", cost="A", map="B",
         render="img/lookmast_v8d.jpg", sketch=None),
    dict(act="II", title="The belt wakes", dur=4, clock="T+3:40:00", real="compressed 10× (~40 s)",
         cam="WS · 40 mm · drifting past a rock",
         action="On a rock ahead, regolith heaves and petal doors open. Missiles tumble out unlit and fire their motors two kilometres clear. Until now the pods were the same temperature as the rock.",
         comm=[("ROCINANTE", "Launch, launch! Cold birds off the rocks, bearing two-one-zero.")],
         rules=["HO2", "HD3"], vfx="Pod doors, late motor ignition", rig=[],
         assets=["EMP-POD", "MSL-V", "BRK"], sound="Nothing, then a hiss.", cost="C", map="B", render=None,
         sketch="panel([rocks(8,1,60,120,40,80,26,28), ship('pod',92,48,2.2,0), ship('pod',76,62,1.8,0), trail('M92,48 Q140,30 200,26','#ff9d7a','0.6 1',0.6), glow(160,32,3,'#ffb080',0.9)], 23)"),
    dict(act="II", title="Countermeasures", dur=5, clock="T+3:45:00", real="1:1",
         cam="MS · 35 mm · along the port flank",
         action="Chaff and flares bloom and a smoke screen unfurls, thinning as it spreads. CIWS barrels spin up and lay kill clouds ahead of the incoming missiles; the laser arrays track, lenses glowing violet, beams invisible. Missiles pop one by one.",
         comm=[("ENDEAVOR", "Chaff and smoke. PD, weapons free.")],
         rules=["D1"], vfx="Tracers, kill clouds, chaff, smoke, intercept flashes",
         rig=["ciws_rpm 0→2400", "ciws_traverse", "laser_power 0→1", "laser_traverse"],
         assets=["EN", "FX-PD"], sound="PDC brrrt through the hull; flare pops.",
         cost="A", map="B", render="img/lookpair_final.jpg", sketch=None),
    dict(act="II", title="Railguns in the rocks", dur=3, clock="T+3:52:00", real="compressed 4× (13 s flight)",
         cam="WS · 50 mm · over the platform's shoulder",
         action="A buried platform unmasks 600 km off the Canterbury's bow and fires a ten-slug pattern straight down its path. With 20 km/s of closing speed the slugs arrive in thirteen seconds; the destroyer can only side-step on RCS.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Canterbury, jink! Slugs on your bow!")],
         rules=["HO1", "HO2", "HO9", "D4"], vfx="Muzzle flashes, slug glints",
         rig=[], assets=["EMP-RG", "DD", "FX-SLUG"], sound="Sharp cracks through the rock (camera on the platform).",
         cost="C", map="B", render=None,
         sketch="panel([rocks(5,1,10,70,50,95,30,32), ship('railplat',60,62,2,-10), glow(38,58,5,'#bfe1ff',0.9), streak(40,58,180,40), streak(40,60,182,44), ship('destroyer',196,40,0.9,180)], 29)"),
    dict(act="II", title="Canterbury", dur=4, clock="T+3:52:13", real="1:1",
         cam="MS · 40 mm · beside the destroyer",
         action="The Canterbury is holed stern to bow. It vents air, its reactor scrams in a flash, and the hull parts in two, tumbling. Its drones drift, suddenly unled.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Canterbury's gone."), ("TIDEBREAK ACTUAL", "Extenuating, you have the net.")],
         rules=["HO9"], vfx="Entry flash, venting, hull break, debris",
         rig=[], assets=["DD", "DD-BRK", "FX-BREAK"], sound="A muffled impact; the comm channel dies to hiss.",
         cost="C", map="B", render=None,
         sketch="panel([ship('destroyer',100,50,1.6,8), glow(118,50,10,'#ffffff',0.8), sparks(126,52,30,30,11), smoke(90,56,16)], 31)"),
    dict(act="II", title="Answer", dur=5, clock="T+3:53:00", real="compressed 26× (slew ~30 s, flight ~100 s)",
         cam="EWS · 135 mm · the Astrid in profile",
         action="The Astrid is coasting, so nothing has to stop: it swings its whole kilometre-long hull to bear, steadies on RCS, and fires down the spinal cannon, a blue-white bloom at the muzzle. Cut: 100 seconds later and 8,000 km away, the platform's rock erupts. The platform could not move.",
         comm=[("TIDEBREAK ACTUAL", "Astrid, turn to bear. Spinal on the platform."), ("ASTRID GUNNERY", "On. Firing."), ("TIDEBREAK ACTUAL", "Remember the Cant.")],
         rules=["O4", "O7"], vfx="Spinal muzzle bloom; impact eruption on the rock",
         rig=[], assets=["AST", "FX-SPINAL", "BRK"], sound="A deep punch through the hull, then silence, then a delayed boom on the cut.",
         cost="C", map="B", render=None,
         sketch="panel([ship('astrid',100,52,1.1,0,true), glow(34,52,14,'#bfe1ff',0.9), plume(30,52,-30,0,3)], 37)"),
    # ------------------------------------------------------------ ACT III
    dict(act="III", title="Screens out", dur=4, clock="T+4:10:00", real="compressed ~40× (minutes)",
         cam="WS · 28 mm · behind the corvettes",
         action="Ahead, dozens of cold hides on the rocks crack open and drones pour out. Rocinante, Tantive IV, Wallfish and Normandy fan out to meet them, PD drones ahead of them.",
         comm=[("TANTIVE IV", "Drones waking on the rocks ahead. Dozens.")],
         rules=["HO4", "D6", "O7"], vfx="Drone swarms (instancing)", rig=[],
         assets=["CV", "DRN-C", "DRN-L", "FX-DRN", "BRK"], sound="A rising whine in the score.",
         cost="C", map="B", render=None,
         sketch="panel([ship('corvette',60,44,2.4,0), ship('corvette',46,62,2,0), ship('corvette',70,70,1.8,0), sparks(180,46,60,70,41), rocks(9,3,190,235,20,90,6,12)], 41)"),
    dict(act="III", title="Return to sender", dur=3, clock="T+4:14:00", real="1:1",
         cam="HUD insert · Extenuating Circumstances",
         action="On the destroyer's plot, a block of drone tracks flips from red to teal: the ones still on a control link are hijacked and turned on their own swarm. The autonomous ones keep coming.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Got their links. Return to sender.")],
         rules=["O5", "HD9"], vfx="HUD, EW overlay", rig=[], assets=["HUD", "FX-EW"],
         sound="Clipped data chatter.", cost="E", map="B", render=None,
         sketch="panel([hud(30,10,180,80), sparks(90,50,24,40,43), '<g opacity=\"0.9\">' + sparks(150,44,24,40,44).replace(/#ffe7b0/g,'#33b3a2') + '</g>', label(34,18,'LINKED ×22 → OURS','#33b3a2'), label(34,86,'AUTONOMOUS ×31 · STILL INBOUND','#e2603f'), glitch(45)], 45)"),
    dict(act="III", title="Normandy", dur=3, clock="T+4:25:00", real="1:1",
         cam="MS · 40 mm · from the Wallfish",
         action="One autonomous drone slips the screen and dives on the Normandy. A plasma bomb goes off against its flank; the corvette breaks up in a spray of light.",
         comm=[("WALLFISH", "One's through, on Normandy—"), ("TIDEBREAK ACTUAL", "Normandy's gone. Close the gap.")],
         rules=["HO4"], vfx="Plasma-bomb flash, break-up", rig=[],
         assets=["CV", "CV-BRK", "DRN-C", "FX-DRN", "FX-BREAK"], sound="A scream of metal through the Wallfish's hull, then nothing.",
         cost="C", map="B", render=None,
         sketch="panel([ship('corvette',120,50,5,-4), glow(128,48,16,'#e3c7ff',0.9), sparks(128,48,40,40,47)], 47)"),
    dict(act="III", title="Turnover", dur=6, clock="T+4:34:10", real="compressed 8× (the flip takes ~49 s)",
         cam="WS · 28 mm · 90° orbit, the smoke screen behind",
         action="Under smoke and an EW peak, one ship at a time, the fleet flips. The Endeavor's stern (drive, reactor, radiators) swings to face Maren and the drive lights: 1 g of braking for 34 minutes, into the lee of the Lee.",
         comm=[("TIDEBREAK ACTUAL", "Turnover. One at a time. Brake for the Lee.")],
         rules=["O13", "D8"], vfx="Main plume, RCS, smoke screen",
         rig=["rcs_bow / rcs_stern pulses", "engine_throttle 0→1"], assets=["EN", "FX-PD"],
         sound="Drive roar building through the hull.", cost="B", map="B", render=None,
         sketch="panel([smoke(60,50,40), ship('endeavorNoShield',140,50,0.9,0), plume(95,50,-60,0,4)], 49)"),
    dict(act="III", title="Into the lee", dur=5, clock="T+5:09:00", real="compressed ~20× (station-keeping)",
         cam="WS · 24 mm · low over the rock's surface",
         action="The Endeavor slides in over boulder fields and settles a few kilometres off the Lee, an 18 km rubble pile. From here the rock stands between the ship and Site 1, and Breakwater, directly beneath it. The rest of the fleet strings out along the rock's shadow line, 50 km apart.",
         comm=[("ENDEAVOR", "In the lee. The rock's between us and Site One.")],
         rules=["D5", "O8", "D2"], vfx="Rock parallax, dust", rig=["rcs_bow / rcs_stern pulses"],
         assets=["EN", "LEE"], sound="Low creaks; RCS thumps.", cost="C", map="C", render=None,
         sketch="panel([rocks(12,1,-40,120,40,160,90,92), ship('endeavorNoShield',170,34,0.8,0)], 53)"),
    dict(act="III", title="Too hot", dur=4, clock="T+5:12:00", real="compressed 5× (fins extend over ~20 s)",
         cam="MS · 35 mm · along the stern shoulders",
         action="Heat alarms. The slot doors slide open and all four fins telescope out, glowing orange as they dump the heat of the Breakers fight. For the first time in two hours the ship is bright.",
         comm=[("ENDEAVOR ENGINEERING", "Sink ninety-four percent. Dumping heat.")],
         rules=["D3", "D5"], vfx="Fin glow ramps, light spill on the hull",
         rig=["radiator_deploy 0→1", "heat 1.9→2.4", "radiator_glow"], assets=["EN"],
         sound="Alarm tones; the fins' hydraulic groan.", cost="A", map="C", render="img/lookaft_s1combat.jpg", sketch=None),
    dict(act="III", title="Fin hit", dur=4, clock="T+5:21:00", real="1:1",
         cam="CU · 50 mm · on the port fin",
         action="A platform on another rock 800 km away has line of sight to the fins sticking out of the Lee's shadow. Ten slugs, 32 seconds of flight; the fins are halfway in when one clips the port fin. It shatters into glowing shards and coolant flashes to vapour.",
         comm=[("ENDEAVOR", "Launch, eight hundred k! Fins in—"), ("ENDEAVOR", "Port fin's gone. Cut it loose.")],
         rules=["HO7", "HO1", "D7"], vfx="Fin shatter, coolant vapour",
         rig=["fin_port 1→shatter (new)", "fin_starboard/dorsal/ventral 1→0.5 (new)"], assets=["EN", "EN-FIN", "FX-FIN", "FX-SLUG"],
         sound="Metal shear through the hull; hiss.", cost="A", map="C", render=None,
         sketch="panel([ship('endeavorNoShield',110,50,1.9,0), glow(176,24,12,'#ff8a3c',0.8), sparks(178,22,40,36,55), smoke(184,20,16), streak(240,4,182,22,'#8fb1ff')], 55)"),
    dict(act="III", title="Broadside", dur=6, clock="T+5:21:40", real="compressed 7× (roll and fire ~40 s)",
         cam="WS → CU · 24 → 50 mm · push onto the port batteries",
         action="Fins stowed, the Endeavor rolls to bring its port turrets to bear; the well batteries rise on their lifts; the M-1Cs wake, arm and fire in sequence at the platform (fixed, so it cannot dodge). Thirty-two seconds later the platform's rock flashes.",
         comm=[("ENDEAVOR", "Roll to port. Batteries up. Fire.")],
         rules=["O6", "O4", "D3"], vfx="M-1C muzzle blasts (tracer style), slug streaks",
         rig=["radiator_deploy →0.12", "rail_traverse", "rail_elevation", "battery_raise 0→1", "rail_wake", "rail_lock", "rail_arm", "shot_a / shot_b", "rail_scales", "rail_heat"],
         assets=["EN", "M1C"], sound="Hammering cracks through the hull, each with its recoil clunk.",
         cost="A", map="C", render="img/house_s1combat.jpg", sketch=None),
    dict(act="III", title="The frigate", dur=3, clock="T+5:24:00", real="1:1",
         cam="WS · 40 mm · over the Donnager",
         action="A Compact frigate that has sat cold behind a rock 60 km away swings out and fires its coilgun; the slug spalls the Endeavor's port belt. The Donnager's four batteries answer.",
         comm=[("DONNAGER", "Frigate off the rock, sixty kilometres. Engaging.")],
         rules=["HO6", "O6"], vfx="Coilgun flash, spall on the Endeavor's belt, Donnager muzzle flashes",
         rig=[], assets=["CF", "GI", "GI-GUN", "EN-DMG", "LEE"], sound="Hammering cracks through the Donnager's hull.",
         cost="C", map="C", render=None,
         sketch="panel([rocks(21,1,150,230,20,90,40,42), ship('hfrigate',150,40,1.6,0), ship('frigate',60,62,1.8,0), streak(80,60,146,42,'#8fb1ff')], 57)"),
    dict(act="III", title="Lance", dur=4, clock="T+5:24:30", real="1:1",
         cam="CU · 28 mm · the Endeavor's nose",
         action="The lance channels on the nose glow. At 40 km, inside the one range where a lance works, the Endeavor fires: a violet-white plasma ring crosses the gap in a blink and the frigate's midsection opens. Escape pods scatter as it breaks.",
         comm=[("ENDEAVOR", "Lance, forty kilometres. Now.")],
         rules=["O12", "O6"], vfx="Lance core glow, plasma bolt, frigate break-up",
         rig=["lance_power 0→1"], assets=["EN", "FX-LANCE", "CF", "FX-BREAK"],
         sound="A rising electric whine, then a crack.", cost="A", map="C", render=None,
         sketch="panel([ship('endeavorNoShield',60,50,1.4,0,true), glow(8,50,8,'#e3c7ff',0.9), '<ellipse cx=\"130\" cy=\"50\" rx=\"3\" ry=\"7\" fill=\"none\" stroke=\"#e3c7ff\" stroke-width=\"1.2\"/>', ship('hfrigate',210,50,1.3,0), glow(208,50,9,'#ffd9a0',0.8)], 59)"),
    # ------------------------------------------------------------ ACT IV
    dict(act="IV", title="The line", dur=4, clock="T+5:40:00", real="1:1",
         cam="HUD insert · Astrid plot",
         action="The plot shows the Lee, Breakwater and Site 1 in one straight line. Missiles fired down it will meet Site 1 and Breakwater nose-first; the other three sites cannot see Breakwater's sky. Readout: Endeavor sink 31 %, fins 3 of 4.",
         comm=[("TIDEBREAK ACTUAL", "That's the line: the Lee, Breakwater, Site One. Wave two on my mark."), ("EXCELSIOR", "Park reports six drones on the shields. Engaging.")],
         rules=["O9", "O3", "HO8", "D11"], vfx="HUD plot", rig=[], assets=["HUD"],
         sound="Sensor tones; the score gathers.", cost="E", map="D", render=None,
         sketch="panel([hud(20,10,200,80), '<line x1=\"40\" y1=\"50\" x2=\"200\" y2=\"50\" stroke=\"#33b3a2\" stroke-width=\"0.6\" stroke-dasharray=\"2 2\"/>', planet(40,50,8,'left'), label(52,44,'SITE 1','#e2603f'), ship('monitor',96,50,0.12,0), label(84,42,'BREAKWATER','#e2603f'), rocks(2,1,186,194,46,54,4,4.5), label(176,42,'THE LEE','#33b3a2'), label(24,86,'ENDEAVOR SINK 31% · FINS 3/4','#33b3a2')], 61)"),
    dict(act="IV", title="Wave two", dur=5, clock="T+5:42:00", real="1:1",
         cam="WS · 24 mm · from the Lee's surface, looking along the line",
         action="The Pillar of Autumn and the Galactica ripple-fire from the lee: decoys, EW missiles and enough real warheads that Breakwater must answer. This wave is meant to be spent. Behind them the Infinity, empty, turns for the Nauvoo.",
         comm=[("TIDEBREAK ACTUAL", "Mark."), ("PILLAR OF AUTUMN", "Wave two away."), ("INFINITY", "Infinity's dry. Heading home.")],
         rules=["O3", "O11"], vfx="Two ripple launches, hundreds of plumes",
         rig=[], assets=["GI", "GI-MAV", "MSL-V", "FX-SWARM", "LEE"],
         sound="Staccato cracks; then the score drops out.", cost="C", map="D", render=None,
         sketch="panel([rocks(14,1,-20,60,60,120,50,52), ship('hedgehog',90,40,1.1,-4), ship('hedgehog',120,62,0.9,-4), trail('M110,38 Q170,28 240,24','#ffd9a0','0.6 0.9',0.8), trail('M136,60 Q190,44 240,40','#ffd9a0','0.6 0.9',0.7), sparks(200,34,30,40,63)], 63)"),
    dict(act="IV", title="The net", dur=5, clock="T+6:40:00", real="compressed 24× (~2 min)",
         cam="WS · 50 mm · over the Extenuating Circumstances",
         action="Hours after the moon spoke, Skerry's rounds arrive. Ahead of the fleet the destroyer's drones light up a spreading cloud of pellets, glittering in their lamps, lying across the lane. The fleet side-steps, drives angled off the line.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Skerry's rounds, right where we said. Canister, bursting ahead."), ("TIDEBREAK ACTUAL", "All ships, come left two degrees.")],
         rules=["HO3", "O13", "D4", "O8"], vfx="Canister cloud glitter in drone lamps",
         rig=[], assets=["DD", "DRN-L", "FX-CAN"], sound="Dust ticking; data chatter.", cost="C", map="D", render=None,
         sketch="panel([ship('destroyer',50,60,1.6,0), sparks(170,40,90,70,67), glow(150,30,10,'#e8f2ff',0.3)], 67)"),
    dict(act="IV", title="The anvil", dur=4, clock="T+6:48:00", real="compressed ~30× (minutes)",
         cam="EWS · 50 mm · over Maren's limb",
         action="Breakwater swings its turrets over the limb of Maren, tracking but silent: the fleet stays far outside the range its guns can hit. Its missile cells open instead. Along its orbit the ring's PD stations unmask.",
         comm=[("ASTRID SENSORS", "Ring's unmasking along the orbit. Breakwater's cells are open.")],
         rules=["HD1", "HD5", "HD7", "HO1"], vfx="Turret motion, cell doors, ring lights",
         rig=[], assets=["BW", "RING", "MAREN"], sound="A low brass sting.", cost="C", map="D", render=None,
         sketch="panel([planet(120,150,110,'left'), ship('monitor',120,30,0.9,0), label(96,14,'BREAKWATER','#e2603f')], 71)"),
    dict(act="IV", title="Blind it", dur=3, clock="T+6:52:00", real="1:1",
         cam="MS · 35 mm · the Endeavor's laser arrays",
         action="The Extenuating Circumstances floods the ring's links; the emplacements drop to their pre-loaded plans. Every laser array in the fleet turns on Breakwater's optics, lenses violet, beams invisible.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Their net's down. The ring's on local control."), ("ENDEAVOR", "All arrays, dazzle Breakwater.")],
         rules=["O5", "HD9"], vfx="Lens glow, EW overlay on inserts",
         rig=["laser_power 1", "laser_traverse", "laser_elevation"], assets=["EN", "FX-EW"],
         sound="Clipped data chatter; lens capacitors whine.", cost="A", map="D", render="img/lookyoke_final.jpg", sketch=None),
    dict(act="IV", title="Wall of fire", dur=5, clock="T+7:02:58", real="slowed 5× (the wave arrives within ~1 s)",
         cam="WS · 40 mm · above Breakwater",
         action="Wave three (the Casaba killers, launched from the approach) arrives in the same second, down the line, nose-on. Breakwater's PD wall fills the sky with tracers and dying decoys, but its lasers see only hardened noses.",
         comm=[("GALACTICA", "Wave three, on target in three, two—")],
         rules=["O3", "HD5", "O9"], vfx="Tracer streams, intercept flashes",
         rig=[], assets=["BW", "FX-PD", "FX-SWARM"], sound="Dense crackle in the score (no air, no bangs).",
         cost="C", map="D", render=None,
         sketch="panel([ship('monitor',120,62,1.0,0), tracers(120,58,-90,60,73), sparks(120,24,50,120,74)], 73)"),
    dict(act="IV", title="Casaba", dur=4, clock="T+7:03:00", real="slowed 3×",
         cam="WS · 35 mm · off Breakwater's quarter",
         action="Three kilometres out, the surviving Casaba charges fire: nuclear plasma spears lance into Breakwater's drive section. Its engines and main thrusters go dark; the monitor is still whole, but it can no longer move.",
         comm=[("ASTRID SENSORS", "Spears in. Breakwater's drive is dark.")],
         rules=["O10"], vfx="Casaba jets, drive section breach, venting",
         rig=[], assets=["BW", "BW-BRK", "FX-CASABA"], sound="White noise, then silence.",
         cost="C", map="D", render=None,
         sketch="panel([ship('monitor',140,50,1.0,0), '<line x1=\"10\" y1=\"20\" x2=\"96\" y2=\"48\" stroke=\"#ffffff\" stroke-width=\"1.3\"/><line x1=\"12\" y1=\"84\" x2=\"96\" y2=\"54\" stroke=\"#ffffff\" stroke-width=\"1.1\"/>', glow(96,50,12,'#ffffff',0.85)], 79)"),
    dict(act="IV", title="Spinal", dur=7, clock="T+7:26:00", real="compressed 30× (slew, fire, 184 s flight)",
         cam="EWS · 200 mm · the Astrid end-on, then Breakwater",
         action="The Astrid, still coasting bow-on at 14,700 km, steadies its whole hull on the crippled monitor and fires. Cut: three minutes later the slug enters through the Casaba breach amidships. Breakwater's back breaks in a chain of secondary flashes.",
         comm=[("TIDEBREAK ACTUAL", "It can't move. Astrid, spinal."), ("ASTRID GUNNERY", "Firing. Impact in three minutes.")],
         rules=["O4", "O10", "HD7"], vfx="Spinal muzzle bloom; impact, spall cone, break-up",
         rig=[], assets=["AST", "BW", "BW-BRK", "FX-SPINAL", "FX-BREAK"],
         sound="Everything drops out; then one deep boom on the cut to the impact.",
         cost="C", map="D", render=None,
         sketch="panel([ship('monitor',150,50,1.2,12), glow(150,50,26,'#ffd9a0',0.8), sparks(150,50,70,60,83), smoke(160,56,30)], 83)"),
    dict(act="IV", title="Terms", dur=4, clock="T+7:45:00", real="1:1",
         cam="MS · 50 mm · slow drift through Breakwater's debris toward the Endeavor",
         action="Debris drifts past the Endeavor: three fins stowed, one stump, scars on the port belt. The CIWS barrels spin down and the lens glow fades.",
         comm=[("EXTENUATING CIRCUMSTANCES", "Actual, MDC is on the line. They're asking for terms."), ("TIDEBREAK ACTUAL", "Tell them Site One goes dark first.")],
         rules=["D7"], vfx="Floating debris", rig=["ciws_rpm →0", "laser_power →0", "heat 2.2"],
         assets=["EN", "EN-FIN", "EN-DMG", "FX-BREAK"], sound="Ticking metal; a long exhale in the score.",
         cost="C", map="D", render=None,
         sketch="panel([ship('endeavorNoShield',150,52,0.9,0), rocks(30,14,10,110,10,90,1,3)], 89)"),
    dict(act="IV", title="Hold", dur=7, clock="T+9:10:00", real="1:1",
         cam="EWS · 35 mm · locked off",
         action="Site 1 is dark. Against Maren's night side, city lights below, the Endeavor runs out its three remaining fins, glowing orange, and dumps the heat of the day. Cut to black.",
         comm=[("ENDEAVOR", "Site One's dark. Fins out.")],
         rules=["D3"], vfx="Fin glow, city lights", rig=["radiator_deploy 0→1 (3 fins)", "heat 2.4", "radiator_glow"],
         assets=["EN", "EN-FIN", "MAREN"], sound="The score resolves; then silence.",
         cost="B", map="D", render="img/hero_s1combat.jpg", sketch=None),
]
