#!/usr/bin/env python3
"""Render the mini-series style options (miniseries/options/*.md) as one reading page.

    pip install markdown-it-py beautifulsoup4
    python3 miniseries/build_options_page.py [--fragment PATH]

Writes miniseries/options.html (a full page). --fragment also writes the page without <html>/<head>/<body>
for the artifact viewer. options/README.md comes first, then each epN_*.md in episode order with its
headings moved down a level, so each file sits under its own episode heading. The look is the plan page's.
"""
import html
import pathlib
import re
import sys

from bs4 import BeautifulSoup
from markdown_it import MarkdownIt

from build_plan_page import CSS, slug

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "options"

EXTRA_CSS = """
main h2.ep{color:var(--lref)}
main h3.opt{border-left:3px solid var(--clock); padding-left:10px}
main h5{font:600 12px/1.4 var(--f-mono); letter-spacing:.06em; color:var(--muted); margin:12px 0 0}
main h6{font:600 12px/1.4 var(--f-mono); color:var(--muted); margin:10px 0 0}
main hr{border:0; border-top:1px solid var(--line); margin:20px 0}
"""


def ep_number(path):
    m = re.match(r"ep(\d+)", path.stem)
    return int(m.group(1)) if m else 99


def render(md, path, demote):
    soup = BeautifulSoup(md.render(path.read_text()), "html.parser")
    if demote:
        for level in range(5, 0, -1):
            for h in soup.find_all(f"h{level}"):
                h.name = f"h{level + 1}"
    return soup


def build():
    md = MarkdownIt("commonmark", {"html": False, "typographer": False}).enable("table").enable("strikethrough")
    files = sorted(SRC.glob("ep*.md"), key=ep_number)
    parts = []
    readme = SRC / "README.md"
    if readme.exists():
        parts.append(render(md, readme, demote=False))
    parts += [render(md, f, demote=True) for f in files]
    soup = BeautifulSoup("".join(p.decode() for p in parts), "html.parser")
    for h in soup.find_all("h1"):
        h.decompose()
    toc, used = [], set()
    for h in soup.find_all(["h2", "h3"]):
        sid = slug(h.get_text())
        while sid in used:
            sid += "-x"
        used.add(sid)
        h["id"] = sid
        text = h.get_text()
        if h.name == "h2" and re.match(r"Ep(isode)?\s*\d", text):
            h["class"] = ["ep"]
        if h.name == "h3" and text.startswith("Option"):
            h["class"] = ["opt"]
        if h.name == "h2" or h.get("class") == ["opt"]:
            em = h.find("em")
            label = (f"{text.split()[1].rstrip(':')} · {em.get_text()}" if h.name == "h3" and em else text.split(" (")[0])
            cls = ' class="sub"' if h.name == "h3" else ""
            toc.append(f'<a href="#{sid}"{cls}>{html.escape(label)}</a>')
    for t in soup.find_all("table"):
        t.wrap(soup.new_tag("div", attrs={"class": "tbl"}))
    head = ('<title>Tidebreak Episode Options</title>\n'
            '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
            '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
            '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700'
            '&family=IBM+Plex+Mono:wght@500;600&family=IBM+Plex+Sans:wght@400;600&display=swap">\n'
            f"<style>{CSS}{EXTRA_CSS}</style>\n")
    body = (f'<div class="wrap">\n<header class="top"><div class="eyebrow">Operation Tidebreak · pre-release mini-series · '
            f'style and storyboard options · round 2</div><h1>Three ways to make each episode</h1><p class="lede">The subjects are '
            f'settled. Each option is a different event, told the way the people in it would really talk, and built from '
            f'the film’s own 3D models. Pick one per '
            f'episode, or mix parts. Generated from <code>miniseries/options/</code>.</p></header>\n'
            f'<nav class="toc" aria-label="Sections">{"".join(toc)}</nav>\n<main>{soup.decode()}</main>\n'
            f'<footer>Generated by miniseries/build_options_page.py from miniseries/options/.</footer>\n</div>\n')
    return head, body, len(files)


def main():
    head, body, n = build()
    page = ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
            + head + "</head>\n<body>\n" + body + "</body>\n</html>\n")
    (ROOT / "options.html").write_text(page)
    if "--fragment" in sys.argv:
        frag = pathlib.Path(sys.argv[sys.argv.index("--fragment") + 1])
        frag.parent.mkdir(parents=True, exist_ok=True)
        frag.write_text(head + body)
    print(f"wrote {ROOT / 'options.html'} ({len(page):,} bytes, {n} episode files)")


if __name__ == "__main__":
    main()
