"""Working numbers for the LREF and Maren doctrines.

Run:  python3 doctrine/working_numbers.py > doctrine/working_numbers.md

Every input below is a production assumption unless the comment cites the
lore posts (pack/lore) or the Blender project (pack/project_docs). The
point of the script is that every number in the doctrines can be checked
and re-derived if an assumption changes.
"""
import math

G = 9.81            # m/s^2
SIGMA = 5.670e-8    # Stefan-Boltzmann, W/m^2/K^4
C = 2.998e8         # m/s
TNT = 4.184e9       # J per tonne TNT
KM = 1e3


def fmt(x, unit="", digits=3):
    """Compact engineering format."""
    if x == 0:
        return f"0 {unit}".strip()
    a = abs(x)
    if a >= 1e5 or a < 1e-2:
        s = f"{x:.{digits-1}e}"
        m, e = s.split("e")
        s = f"{m}e{int(e)}"
    elif a >= 100:
        s = f"{x:,.0f}"
    elif a >= 10:
        s = f"{x:.1f}"
    else:
        s = f"{x:.2f}"
    return f"{s} {unit}".strip()


def dur(t):
    """Seconds to a readable duration."""
    if t < 1:
        return f"{t*1000:.0f} ms"
    if t < 120:
        return f"{t:.1f} s"
    if t < 7200:
        return f"{t/60:.1f} min"
    if t < 2 * 86400:
        return f"{t/3600:.1f} h"
    return f"{t/86400:.1f} d"


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


print("# Working numbers (generated)\n")
print("Generated by `doctrine/working_numbers.py`. Both doctrines cite these "
      "tables. Inputs are production assumptions unless marked *lore* or "
      "*model*. Change an input and re-run to see what moves.\n")

# ---------------------------------------------------------------- 1. lasers
print("## 1. Lasers: spot size, intensity, time to kill\n")
print("Spot = Airy first-null diameter 2.44·λ·R/D, holding 84 % of the "
      "power; a 1.5x jitter/aberration allowance is applied to the diameter. "
      "Ground lasers lose 30 % in the atmosphere.\n")

LASERS = [
    # name, aperture m, wavelength m, beam power W, wall-plug eff, transmission
    ("LREF laser focusing array (LFA)", 3.3, 350e-9, 25e6, 0.25, 1.0),
    ("LREF PD laser", 1.6, 350e-9, 5e6, 0.25, 1.0),
    ("Breakwater PD laser", 2.0, 530e-9, 10e6, 0.25, 1.0),
    ("Maren ground laser (per site)", 10.0, 1.06e-6, 2e9, 0.30, 0.7),
    ("Skerry laser battery (airless)", 8.0, 530e-9, 1e9, 0.30, 1.0),
]
print(table(["Laser", "Aperture", "λ", "Beam power", "Waste heat while firing"],
            [(n, f"{D} m", f"{lam*1e9:.0f} nm", fmt(P, "W"), fmt(P / e - P, "W"))
             for n, D, lam, P, e, tr in LASERS]))
print()

# fluence (J/m^2) needed for each effect
EFFECTS = [
    ("dazzle a sensor (saturate)", 1e1, True),      # W/m^2, intensity threshold
    ("kill a seeker window", 1e6, False),
    ("burn a radiator fin panel", 2e7, False),
    ("burn a missile's side skin", 3e7, False),
    ("burn a hardened missile nose (10 cm C-C)", 5e9, False),
    ("melt through 0.72 m hull belt (model)", 2e10, False),
]
RANGES_KM = [100, 1_000, 10_000, 50_000, 100_000, 300_000]
JITTER = 1.5


def spot(D, lam, R):
    return JITTER * 2.44 * lam * R / D


def intensity(P, D, lam, R, tr=1.0):
    d = spot(D, lam, R)
    return 0.84 * P * tr / (math.pi * d * d / 4)


for n, D, lam, P, e, tr in LASERS:
    rows = []
    for rk in RANGES_KM:
        R = rk * KM
        I = intensity(P, D, lam, R, tr)
        row = [f"{rk:,} km", fmt(spot(D, lam, R), "m"), fmt(I, "W/m²")]
        for name, F, is_int in EFFECTS[1:]:
            t = F / I
            row.append(dur(t) if t < 3 * 3600 else "—")
        rows.append(row)
    print(f"**{n}**\n")
    print(table(["Range", "Spot", "Intensity"] + [x[0] for x in EFFECTS[1:]], rows))
    print()

print("Dazzle needs only ~10 W/m² on a sensor aperture, so every laser above "
      "dazzles out past 10⁶ km; the practical limit is pointing and tracking, "
      "not power. A radiator fin is a 20 MJ/m² target; an armoured hull is "
      "a 20 GJ/m² target. That thousandfold gap is why lasers strip fins, "
      "sensors and missiles, and why guns and warheads kill hulls.\n")

# ------------------------------------------------------ 2. kinetics vs dodge
print("## 2. Kinetics: time of flight against a dodging target\n")
GUNS = [
    # name, slug kg, muzzle m/s
    ("LREF M-1C twin railcannon (per gun)", 10, 25e3),
    ("Astrid spinal cannon", 500, 60e3),
    ("Breakwater heavy railgun", 50, 30e3),
    ("Breakers railgun platform", 10, 25e3),
    ("Skerry mass driver (smart rock)", 10_000, 15.5e3),
]
print(table(["Gun", "Slug", "Muzzle velocity", "Muzzle energy", "TNT equiv."],
            [(n, fmt(m, "kg"), fmt(v / KM, "km/s"), fmt(0.5 * m * v * v, "J"),
              fmt(0.5 * m * v * v / TNT, "t"))
             for n, m, v in GUNS]))
print()

TARGETS = [
    # name, lateral accel m/s^2, distance it must move to clear, reaction s
    ("capital ship on RCS only (0.1 g), end-on", 0.1 * G, 150, 3),
    ("capital ship on RCS only (0.1 g), broadside", 0.1 * G, 700, 3),
    ("capital ship, main drive across the line of fire (1 g)", 1.0 * G, 700, 5),
    ("Breakwater monitor (0.05 g)", 0.05 * G, 800, 3),
    ("Breakwater, drive crippled (0.005 g RCS)", 0.005 * G, 800, 3),
    ("frigate (2 g)", 2 * G, 300, 2),
    ("corvette (4 g)", 4 * G, 100, 1),
]


def escape_range(v_close, a, d, t_react):
    """Largest range at which the target can NOT clear d before impact."""
    t = t_react + math.sqrt(2 * d / a)
    return v_close * t, t


rows = []
for gname, m, v in GUNS[:4]:
    for tname, a, d, tr in TARGETS:
        for vc in (0, 20e3):
            R, t = escape_range(v + vc, a, d, tr)
            rows.append([gname, tname, f"{vc/KM:.0f} km/s",
                         fmt(R / KM, "km"), dur(t)])
print("*No-escape range*: inside it, the target cannot move far enough "
      "between seeing the shot and the slug arriving. It assumes the shooter "
      "sees the launch flash instantly (the light-lag is added to the "
      "reaction time) and fires one slug at the target's predicted centre. "
      "Salvo patterns stretch these ranges roughly 2-4x at the cost of "
      "hit probability per slug.\n")
print(table(["Gun", "Target", "Extra closing speed", "No-escape range",
             "Time the target needs"], rows))
print()

print("**Time of flight by range** (slug speed + closing speed):\n")
rows = []
for rk in (100, 1_000, 10_000, 50_000, 100_000):
    R = rk * KM
    rows.append([f"{rk:,} km"] + [dur(R / (v + vc)) for _, _, v in GUNS
                                  for vc in (0,)] + [dur(R / (25e3 + 20e3))])
print(table(["Range"] + [g[0] for g in GUNS] + ["M-1C + 20 km/s closing"], rows))
print()

# ---------------------------------------------------------------- 3. missiles
print("## 3. Missiles: flight time\n")
MISSILES = [
    # name, accel m/s^2, dv m/s, reserve for terminal (fraction)
    ("Hedgehog capital-ship killer", 30 * G, 150e3, 0.25),
    ("Hedgehog multi-pack (small)", 50 * G, 60e3, 0.25),
    ("Endeavor VLS precision missile", 40 * G, 100e3, 0.25),
    ("Breakers pod missile", 40 * G, 40e3, 0.25),
    ("Compact strike drone", 10 * G, 30e3, 0.3),
]


def missile_tof(R, a, dv, reserve, v0=0.0):
    """Boost with (1-reserve)*dv, then coast. v0 = launcher closing speed."""
    dv_use = dv * (1 - reserve)
    tb = dv_use / a
    db = v0 * tb + 0.5 * a * tb * tb
    if db >= R:
        # reach target while still boosting
        t = (-v0 + math.sqrt(v0 * v0 + 2 * a * R)) / a
        return t, v0 + a * t
    vc = v0 + dv_use
    return tb + (R - db) / vc, vc


rows = []
for name, a, dv, res in MISSILES:
    row = [name, f"{a/G:.0f} g", fmt(dv / KM, "km/s")]
    for rk in (10_000, 100_000, 300_000, 1_000_000):
        t, vc = missile_tof(rk * KM, a, dv, res)
        row.append(f"{dur(t)} ({vc/KM:.0f} km/s)")
    rows.append(row)
print("Launched from rest relative to the target; 25-30 % of Δv held back for "
      "terminal manoeuvre. Brackets give the closing speed at arrival.\n")
print(table(["Missile", "Accel", "Δv", "10,000 km", "100,000 km", "300,000 km",
             "1,000,000 km"], rows))
print()

print("**Time a missile spends in each defensive band** at closing speed "
      "`Vc` (this is the defender's whole engagement window for that layer):\n")
BANDS = [("100,000 → 10,000 km", 100_000, 10_000),
         ("10,000 → 1,000 km", 10_000, 1_000),
         ("1,000 → 100 km", 1_000, 100),
         ("100 → 10 km", 100, 10),
         ("10 → 2 km (inside Casaba standoff)", 10, 2)]
rows = []
for bname, a, b in BANDS:
    rows.append([bname] + [dur((a - b) * KM / vc) for vc in (20e3, 60e3, 120e3)])
print(table(["Band", "Vc 20 km/s", "Vc 60 km/s", "Vc 120 km/s"], rows))
print()

# ---------------------------------------------------------------- 4. heat
print("## 4. Heat\n")


def rad_power(area_one_face, T, eps=0.9, view=0.8):
    return 2 * area_one_face * eps * SIGMA * T ** 4 * view


FINS = [
    # name, one-face area m^2 (measured off the size chart), model/lore note
    ("Endeavor, 4 fins (model: ~257 m root x ~141 m span each)", 4 * 18_000),
    ("Astrid, 8 stacked fins (lore; ~270 m x ~330 m each)", 8 * 45_000),
    ("Garibaldi-Ivanova frigate (art)", 4 * 3_000),
    ("Destroyer (art)", 2 * 1_500),
]
rows = []
for name, A in FINS:
    rows.append([name, fmt(A, "m²")] +
                [fmt(rad_power(A, T), "W") for T in (600, 900, 1200, 1500)])
print("Two-sided fins, emissivity 0.9, view factor 0.8 (fins partly see each "
      "other and the hull).\n")
print(table(["Radiators", "Area per face", "600 K (dull, IR only)",
             "900 K (faint red)", "1,200 K (orange)", "1,500 K (bright orange)"],
            rows))
print()

LOADS = [
    # name, W
    ("8 LFAs firing (25 % wall-plug)", 8 * 25e6 * 3),
    ("8 PD lasers firing", 8 * 5e6 * 3),
    ("12 M-1C guns, one shot each per 15 s (50 % eff.)", 12 * (0.5 * 10 * 25e3 ** 2) / 15),
    ("Reactor waste to supply the guns (40 % conversion)", 12 * (0.5 * 10 * 25e3 ** 2) * 2 / 15 * 1.5),
    ("Reactor waste to supply the lasers", (8 * 25e6 + 8 * 5e6) * 4 * 1.5),
    ("Hotel, sensors, drive support at 1 g", 1.5e9),
]
total = sum(w for _, w in LOADS)
print("**Endeavor full-combat heat load** (everything firing):\n")
print(table(["Source", "Heat"], [(n, fmt(w, "W")) for n, w in LOADS] +
            [("**Total**", f"**{fmt(total, 'W')}**")]))
print()

SINKS = [
    ("Endeavor heat sink (assumed 20 TJ)", 20e12, total),
    ("Endeavor sink, guns silent (lasers + hotel)", 20e12,
     LOADS[0][1] + LOADS[1][1] + LOADS[4][1] + LOADS[5][1]),
    ("Endeavor sink, cruising dark (hotel only)", 20e12, LOADS[5][1]),
    ("Astrid heat sink (assumed 60 TJ), full combat ~25 GW", 60e12, 25e9),
    ("Frigate sink (assumed 3 TJ), PD firing ~2 GW", 3e12, 2e9),
]
print(table(["Case", "Sink", "Load", "Time until full"],
            [(n, fmt(S, "J"), fmt(L, "W"), dur(S / L)) for n, S, L in SINKS]))
print()
spinal_heat = 0.5 * 500 * 60e3 ** 2 * (1 + 1.5)   # gun losses + reactor waste
print(f"One spinal shot dumps about {fmt(spinal_heat, 'J')} of heat "
      f"(gun losses plus reactor waste). With the Astrid's fins out at 1,200 K "
      f"that takes {dur(spinal_heat / rad_power(8*45_000, 1200))} to reject; "
      f"on a 60 TJ sink it allows about {60e12/spinal_heat:.0f} shots dark.\n")

# ---------------------------------------------------------------- 5. detection
print("## 5. Who sees whom\n")
F_MIN = 1e-15   # W/m^2 in-band flux a 1 m cooled IR telescope detects in a quick stare
SOURCES = [
    ("Endeavor main drive at 1 g (plume)", 1e14),
    ("Endeavor fins out, 1,200 K", rad_power(4 * 18_000, 1200)),
    ("Astrid fins out, 1,200 K", rad_power(8 * 45_000, 1200)),
    ("Endeavor dark: fins in, 300 K hull (~5.6e5 m²)", 5.6e5 * 0.9 * SIGMA * 300 ** 4),
    ("Frigate dark, 300 K hull", 1.2e5 * 0.9 * SIGMA * 300 ** 4),
    ("Breakers emplacement at rock temperature", 0.0),
]
rows = []
for n, P in SOURCES:
    if P == 0:
        rows.append([n, "same as the rock", "only when it moves, fires or is radar-mapped"])
        continue
    R = math.sqrt(P / (4 * math.pi * F_MIN))
    rows.append([n, fmt(P, "W"), f"{fmt(R/KM, 'km')} ({R/1.496e11:.2g} AU)"])
print(f"Detection range for a 1 m cooled IR telescope that needs "
      f"{F_MIN:g} W/m² (a quick stare against deep space; long stares do "
      f"better, a bright planet or the warm Breakers behind the target does worse).\n")
print(table(["Source", "Radiated power", "Detection range"], rows))
print()

# radar
def radar_range(P, D, lam, sigma_t, T_sys=100, B=1e3, snr=13, eff=0.6):
    Gain = eff * (math.pi * D / lam) ** 2
    k = 1.380649e-23
    return (P * Gain ** 2 * lam ** 2 * sigma_t /
            ((4 * math.pi) ** 3 * k * T_sys * B * snr)) ** 0.25


rows = []
for tgt, s in (("1 m² (missile, drone, emplacement mast)", 1.0),
               ("0.01 m² (a 10 kg slug, nose-on)", 0.01),
               ("1,000 m² (frigate)", 1e3)):
    rows.append([tgt, fmt(radar_range(10e6, 100, 0.03, s) / KM, "km"),
                 fmt(radar_range(1e6, 12, 0.03, s) / KM, "km")])
print("**Radar** (X-band, 3 cm; 1 kHz integration; SNR 13 dB):\n")
print(table(["Target", "Astrid AVPSA (100 m dish, 10 MW)",
             "Endeavor phased array (12 m, 1 MW)"], rows))
print()

print("**Light-lag** (one way):\n")
print(table(["Distance", "Lag"],
            [(f"{d:,} km", dur(d * KM / C)) for d in
             (42_000, 100_000, 200_000, 380_000, 450_000, 1_000_000)]))
print()

# ---------------------------------------------------------------- 6. manoeuvre
print("## 6. Manoeuvre\n")
print("**Flip (180°) time**, limited by the acceleration felt at the ship's "
      "ends (bang-bang rotation: t = 2π·√(r/a_end)):\n")
SHIPS = [("Astrid (1,660 m)", 830), ("Endeavor (1,194 m)", 597),
         ("Frigate (420 m)", 210), ("Destroyer (200 m)", 100), ("Corvette (100 m)", 50)]
print(table(["Ship", "ends at 0.5 g", "ends at 1 g", "ends at 3 g"],
            [(n, dur(2 * math.pi * math.sqrt(r / (0.5 * G))),
              dur(2 * math.pi * math.sqrt(r / G)),
              dur(2 * math.pi * math.sqrt(r / (3 * G)))) for n, r in SHIPS]))
print()

print("**Braking from an arrival speed at 1 g** (the draft's 180 km/s arrival "
      "and slower alternatives):\n")
rows = []
for v in (180e3, 100e3, 50e3, 20e3):
    rows.append([fmt(v / KM, "km/s"), dur(v / G), fmt(v * v / (2 * G) / KM, "km")])
print(table(["Arrival speed", "Burn time", "Distance covered while braking"], rows))
print()


def approach(d, a, v_cruise):
    """Accelerate to v_cruise, coast, brake at the same a. Returns time."""
    d_acc = v_cruise ** 2 / (2 * a)
    if 2 * d_acc >= d:
        return 2 * math.sqrt(d / a), math.sqrt(a * d)
    return 2 * v_cruise / a + (d - 2 * d_acc) / v_cruise, v_cruise


rows = []
for vc in (10e3, 20e3, 30e3, 60e3, 1e9):
    t, vmax = approach(410_000 * KM, G, vc)
    rows.append(["brachistochrone" if vc > 1e8 else fmt(vc / KM, "km/s"),
                 fmt(vmax / KM, "km/s"), dur(t)])
print("**Approach from a warp exit 450,000 km out to Breakwater's orbit "
      "(410,000 km of travel) at 1 g**:\n")
print(table(["Cruise speed cap", "Peak speed", "Total time"], rows))
print()

print("**What a pebble is worth at the closing speed** (why the defender "
      "wants the attacker fast):\n")
rows = []
for v in (5e3, 20e3, 60e3, 180e3):
    rows.append([fmt(v / KM, "km/s")] +
                [f"{fmt(0.5*m*v*v, 'J')} ({fmt(0.5*m*v*v/TNT*1000, 'kg')} TNT)"
                 for m in (0.001, 1.0, 100.0)])
print(table(["Closing speed", "1 g grain", "1 kg rock", "100 kg rock"], rows))
print()

# ---------------------------------------------------------------- 7. nuclear
print("## 7. Nuclear effects in vacuum\n")
print("No air means no blast wave. A bare burst kills by X-rays (≈70 % of "
      "yield) heating the target's surface, which spalls off. A Casaba "
      "howitzer throws a fraction of its yield as a narrow plasma jet.\n")
rows = []
for yld_kt in (100, 1000):
    E = yld_kt * 1e3 * TNT * 0.7
    rows.append([f"{yld_kt:,} kt bare burst"] +
                [fmt(E / (4 * math.pi * (r * KM) ** 2), "J/m²")
                 for r in (0.1, 1, 10, 100)])
for yld_kt, frac, half in ((20, 0.25, 0.01), (100, 0.25, 0.01)):
    E = yld_kt * 1e3 * TNT * frac
    rows.append([f"{yld_kt} kt Casaba, {frac:.0%} into a {half} rad jet"] +
                [fmt(E / (math.pi * (half * r * KM) ** 2), "J/m²")
                 for r in (0.1, 1, 10, 100)])
print(table(["Warhead", "at 100 m", "at 1 km", "at 10 km", "at 100 km"], rows))
print()
def kill_radius(E_per_sr_or_total, F, casaba_half=None):
    if casaba_half is None:   # bare burst, isotropic
        return math.sqrt(E_per_sr_or_total / (4 * math.pi * F))
    return math.sqrt(E_per_sr_or_total / (math.pi * casaba_half ** 2 * F))


rows = []
for label, E, half in (("100 kt bare burst", 100e3 * TNT * 0.7, None),
                       ("1 Mt bare burst", 1e6 * TNT * 0.7, None),
                       ("20 kt Casaba (0.01 rad)", 20e3 * TNT * 0.25, 0.01),
                       ("100 kt Casaba (0.01 rad)", 100e3 * TNT * 0.25, 0.01)):
    rows.append([label] + [fmt(kill_radius(E, F, half) / KM, "km")
                           for F in (2e7, 5e9, 2e10)])
print("**Kill radius** (distance inside which the fluence exceeds the §1 "
      "threshold; for a Casaba only along the jet, whose spot is 2 % of the "
      "range across):\n")
print(table(["Warhead", "radiator fins, sensors", "hardened missile nose",
             "0.72 m hull belt"], rows))
print()
print("So a bare burst must land within ~100-250 m to breach a hull, and "
      "strips fins out to ~1-3 km. A Casaba breaches a hull belt from 2-4 km "
      "(outside the CIWS kill-cloud zone, see §8) if its jet is pointed true.\n")

# ---------------------------------------------------------------- 8. point defence
print("## 8. Point defence: how many missiles one wave has to spend\n")
print("Laser kills are integrated over the missile's run-in: each kill takes "
      "the burn time at that range plus a retarget time. *Nose-on* means the "
      "laser sees the hardened nose (5 GJ/m²); *side-on* means it sees a "
      "spinning side skin (3 × 30 MJ/m², the spin spreads the heat). CIWS "
      "kill clouds are counted separately.\n")


def laser_kills(D, lam, P, tr, F, Vc, R_max, R_min, t_re):
    n, R, dR = 0.0, R_max, (R_max - R_min) / 20000
    while R > R_min:
        t_kill = F / intensity(P, D, lam, R, tr)
        n += (dR / Vc) / (t_kill + t_re)
        R -= dR
    return n


PD_CASES = [
    # name, (D, lam, P, tr), count, retarget s, max tracking range m
    ("Endeavor: 8 LFAs", (3.3, 350e-9, 25e6, 1.0), 8, 1.0, 30_000 * KM),
    ("Endeavor: 8 PD lasers", (1.6, 350e-9, 5e6, 1.0), 8, 0.5, 5_000 * KM),
    ("Breakwater: 24 PD lasers", (2.0, 530e-9, 10e6, 1.0), 24, 0.5, 10_000 * KM),
    ("Maren: 4 ground sites (if all see the wave)", (10.0, 1.06e-6, 2e9, 0.7), 4, 2.0, 150_000 * KM),
]
rows = []
for name, (D, lam, P, tr), count, t_re, R_max in PD_CASES:
    row = [name]
    for Vc in (45e3, 100e3):
        for F in (9e7, 5e9):
            row.append(f"{count * laser_kills(D, lam, P, tr, F, Vc, R_max, 50 * KM, t_re):,.0f}")
    rows.append(row)
print(table(["Defence", "side-on, 45 km/s", "nose-on, 45 km/s",
             "side-on, 100 km/s", "nose-on, 100 km/s"], rows))
print()

print("**CIWS kill clouds.** A 7-barrel mount throws ~280 rounds/s at ~2 km/s. "
      "A missile closing at tens of km/s cannot see or dodge a pellet cloud in "
      "the last fraction of a second, so the cloud kills with the missile's own "
      "speed; a 50 g pellet at 60 km/s carries 90 MJ. Covering one missile's "
      "last-second uncertainty (~50 m × 50 m) takes ~1,500 rounds, about 5 s "
      "of one mount's fire.\n")
rows = []
for X in (5, 10, 20, 30):
    t_round = X * KM / 2e3
    row = [f"{X} km", dur(t_round)]
    for Vc in (45e3, 100e3):
        t_last = X * KM / Vc
        row.append(f"{Vc*t_round/KM:,.0f} km / {0.5*30*G*t_last**2:,.0f} m")
    rows.append(row)
print(table(["Cloud placed at", "Round flight time",
             "45 km/s: lead distance / missile divert in last leg",
             "100 km/s: lead distance / missile divert"], rows))
print()
print("A 16-mount battery therefore kills roughly 3 missiles a second while "
      "the wave arrives, and nothing that detonates outside ~5 km: a Casaba "
      "standing off at 2-4 km must be killed by the clouds at 5-30 km or by "
      "the lasers before that.\n")


def site_kills_vs_orbit(off_deg, v=80e3, start=120_000 * KM, t_re=2.0):
    """One ground site against a wave aimed at a target in synchronous orbit
    straight above it. The wave flies a straight line to the target, arriving
    off_deg from the target's zenith; the laser burns the nose or the flank,
    whichever the aspect along the path makes quicker; the site fires only
    above 20 degrees elevation."""
    site, tgt = (0.0, 6_400 * KM), (0.0, 42_164 * KM)
    a = math.radians(off_deg)
    u = (math.sin(a), math.cos(a))      # from the target toward the incoming wave
    n, k = 20000, 0.0
    dt = start / v / n
    for i in range(n):
        d = start * (1 - (i + 0.5) / n)
        mx, my = tgt[0] + u[0] * d, tgt[1] + u[1] * d
        dx, dy = site[0] - mx, site[1] - my
        R = math.hypot(dx, dy)
        if math.degrees(math.asin((my - site[1]) / R)) < 20:
            continue
        alpha = math.acos(max(-1.0, min(1.0, (-u[0] * dx - u[1] * dy) / R)))
        F = 9e7 / max(math.sin(alpha), 1e-9)
        if alpha < math.pi / 2:
            F = min(F, 5e9 / max(math.cos(alpha), 1e-9))
        k += dt / (F / intensity(2e9, 10.0, 1.06e-6, R, 0.7) + t_re)
    return k


print("**A ground site against a wave aimed at an orbital target.** The table "
      "above assumes missiles that run in to ~50 km of the laser. A wave aimed "
      "at a monitor in synchronous orbit over the site (42,164 km) never comes "
      "closer than ~35,800 km, where one 2 GW site needs ~12-15 s per flank "
      "kill. One site, a wave closing at 80 km/s from 120,000 km out:\n")
rows = [[f"{off}°", f"{site_kills_vs_orbit(off):.0f}"] for off in (0, 15, 30, 48, 90)]
print(table(["Wave arrives this far off the target's zenith", "Kills by the site"], rows))
print()
print("So against Breakwater, Site 1 matters little whatever the angle: the "
      "angle is chosen to keep misses and wreckage off the planet (LREF O9), "
      "not to hide from the site. A neighbouring site sees such a wave only "
      "early in its flight, far off and nearly nose-on, so it adds a handful "
      "of kills at most.\n")
